import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  analyzeMessageTemplate,
  checkI18nContractOutputs,
  createI18nContractOutputs,
  formatGeneratedSource,
  parseAddGameWarningContract,
  parseEnglishContract,
  parseDesktopCommandErrorContract,
  parseLumaContract,
  parseNvapiContract,
  parseOptiscalerContract,
  parseRenodxContract,
  parsePluralCategories,
  validateExternalCatalogBoundaries,
} from './i18n-contracts.mjs';
import { parseJsonSource } from './i18n-contracts/parser.mjs';
import { createContractVersion, createSemanticContract } from './i18n-contracts/contract.mjs';
import { validateEditorialPolicy } from './i18n-contracts/validator.mjs';
import { PLACEHOLDER_CONTRACT_CASES } from '../ui/src/shared/i18n/messages/placeholder-contract-cases.ts';

const EXPECTED_CONTRACT_VERSION =
  'i18n-v2:42e4900cc1df96e25093ce1042e2e24319a986dce1ea20aae0d30fc462da382f';

function isAccessibilityDeliveryNamedKey(key) {
  return (
    /(?:^|\.)(?:a11y|accessibility|aria|srLabel|srOnly|screenReader|visuallyHidden)(?:\.|$)/i.test(
      key,
    ) ||
    /(?:^|\.)(?:a11y|accessibility|aria|srLabel|srOnly|screenReader|visuallyHidden)(?=[A-Z])|A11y|Accessibility|Aria|SrLabel|SrOnly|ScreenReader|VisuallyHidden/.test(
      key,
    )
  );
}

test('contract generation is deterministic and committed outputs are current', async () => {
  const first = await createI18nContractOutputs();
  const second = await createI18nContractOutputs();

  assert.deepEqual([...first], [...second]);
  assert.deepEqual(await checkI18nContractOutputs(first), []);
  assert.equal(first.size, 7);
  for (const source of first.values()) {
    assert.match(source, /^\/\/ This file is generated by `pnpm i18n:generate`\./);
  }
  const versionSource = first.entries().find(([file]) => file.endsWith('contract-version.ts'))?.[1];
  assert.match(versionSource, new RegExp(EXPECTED_CONTRACT_VERSION));
});

test('message keys describe product ownership instead of accessibility delivery mechanics', async () => {
  const source = await readFile(
    new URL('../ui/src/shared/i18n/messages/en.ts', import.meta.url),
    'utf8',
  );
  const implementationNamedKeys = Object.keys(parseEnglishContract(source)).filter(
    isAccessibilityDeliveryNamedKey,
  );

  assert.deepEqual(
    implementationNamedKeys,
    [],
    'Accessible copy must belong to its product domain; do not encode delivery mechanics such as accessibility, a11y, ARIA, screen-reader-only, or visually-hidden in message keys.',
  );
});

test('message-key naming policy covers dotted, prefixed, and camel-case delivery terms', () => {
  for (const key of [
    'a11y.libraryDownload',
    'library.accessibility.download',
    'library.ariaLabel',
    'library.downloadAriaLabel',
    'library.downloadSrOnly',
    'library.screenReaderHint',
    'library.visuallyHiddenStatus',
  ]) {
    assert.equal(isAccessibilityDeliveryNamedKey(key), true, key);
  }

  for (const key of [
    'library.downloadLabel',
    'library.downloadDescription',
    'settings.inputLabel',
  ]) {
    assert.equal(isAccessibilityDeliveryNamedKey(key), false, key);
  }
});

test('placeholder analyzer matches the shared contract table', () => {
  for (const fixture of PLACEHOLDER_CONTRACT_CASES) {
    assert.deepEqual(analyzeMessageTemplate(fixture.template), {
      valid: fixture.valid,
      placeholders: fixture.placeholders,
    });
  }
});

test('English contract parser rejects malformed tagged messages', () => {
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: plural('count', { one: '{count} item' }),
        });
      `),
    /plural branches must be exactly one and other/,
  );
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: select('tone', { other: 'Default' }),
        });
      `),
    /select branches must include other and at least one named case/,
  );
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: '{valid} then {bad-name}',
        });
      `),
    /contains invalid placeholder syntax/,
  );
});

test('generator diagnostics identify the source file and message key', () => {
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          'broken.message': '{valid} then {bad-name}',
        });
      `),
    /ui\/src\/shared\/i18n\/messages\/en\.ts: English message broken\.message contains invalid placeholder syntax/,
  );
});

test('source parsers reject malformed TypeScript and JSON with actionable diagnostics', () => {
  assert.throws(
    () => parseEnglishContract('const en = defineSourceCatalog({ broken: "value"; });'),
    /ui\/src\/shared\/i18n\/messages\/en\.ts: TypeScript syntax error at 1:\d+:/,
  );
  assert.throws(() => parseJsonSource('{"broken":'), /invalid JSON/);
});

test('desktop command-error manifest validates codes, references, and strict shapes', () => {
  const english = parseEnglishContract(`
    const en = defineSourceCatalog({
      'error.message': 'Failed.',
      'error.action': 'Try again.',
      'warning.count': plural('count', { one: 'One', other: '{count} items' }),
    });
  `);
  const valid = {
    schemaVersion: 1,
    commandErrors: [
      {
        code: 'operation_failed',
        rustVariant: 'OperationFailed',
        messageKey: 'error.message',
        severity: 'error',
        actions: ['retry'],
      },
    ],
    suggestedActions: [{ code: 'retry', messageKey: 'error.action' }],
  };

  assert.equal(parseDesktopCommandErrorContract(valid, english).schemaVersion, 1);
  assert.throws(
    () => parseDesktopCommandErrorContract({ ...valid, schemaVersion: 2 }, english),
    /unsupported schemaVersion/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        { ...valid, commandErrors: [...valid.commandErrors, valid.commandErrors[0]] },
        english,
      ),
    /duplicate code/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], code: `a${'b'.repeat(64)}` }],
        },
        english,
      ),
    /invalid machine code/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], rustVariant: 'invalid_variant' }],
        },
        english,
      ),
    /invalid rustVariant/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], messageKey: 'error.missing' }],
        },
        english,
      ),
    /missing English message/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          suggestedActions: [{ ...valid.suggestedActions[0], messageKey: 'error.missing' }],
        },
        english,
      ),
    /missing English message/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], actions: ['missing'] }],
        },
        english,
      ),
    /unknown suggested action/,
  );
  assert.throws(
    () => parseDesktopCommandErrorContract({ ...valid, unexpected: true }, english),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], recoveryBundlePath: false }],
        },
        english,
      ),
    /must be true when present/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [
            { ...valid.commandErrors[0], severity: 'warning', recoveryBundlePath: true },
          ],
        },
        english,
      ),
    /exposes a recovery path but is not an error/,
  );
});

test('add-game warning manifest validates references, parameters, and strict shapes', () => {
  const english = parseEnglishContract(`
    const en = defineSourceCatalog({
      'warning.count': plural('count', { one: 'One', other: '{count} items' }),
    });
  `);
  const valid = {
    schemaVersion: 1,
    addGameWarnings: [
      {
        code: 'items_found',
        messageKey: 'warning.count',
        parameters: { count: 'positive_integer' },
      },
    ],
  };

  assert.equal(parseAddGameWarningContract(valid, english).schemaVersion, 1);
  assert.throws(
    () => parseAddGameWarningContract({ ...valid, unexpected: true }, english),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseAddGameWarningContract(
        {
          ...valid,
          addGameWarnings: [
            { ...valid.addGameWarnings[0], parameters: { path: 'non_blank_string' } },
          ],
        },
        english,
      ),
    /do not match English message/,
  );
  assert.throws(
    () =>
      parseAddGameWarningContract(
        {
          ...valid,
          addGameWarnings: [
            { ...valid.addGameWarnings[0], parameters: { count: 'arbitrary_text' } },
          ],
        },
        english,
      ),
    /invalid type/,
  );
});

test('stale detection reports missing and mismatched generated outputs', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'renderpilot-i18n-stale-'));
  const missingPath = path.join(directory, 'missing.ts');
  const mismatchedPath = path.join(directory, 'mismatched.ts');

  try {
    await writeFile(mismatchedPath, 'actual\n', 'utf8');
    const stale = await checkI18nContractOutputs(
      new Map([
        [missingPath, 'expected\n'],
        [mismatchedPath, 'expected\n'],
      ]),
    );

    assert.equal(stale.length, 2);
    assert.equal(stale[0].endsWith('missing.ts'), true);
    assert.equal(stale[1].endsWith('mismatched.ts'), true);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('contract records use locale-independent ordinal key order', () => {
  const contract = parseEnglishContract(`
    const en = defineSourceCatalog({
      'a_b': 'underscore',
      'a.b': 'dot',
      'a-b': 'dash',
    });
  `);

  assert.deepEqual(Object.keys(contract), ['a-b', 'a.b', 'a_b']);
});

test('contract version changes when an external key or reviewed source changes', () => {
  const createVersion = (sourceCatalog) =>
    createContractVersion(
      createSemanticContract({
        english: {},
        pluralCategories: {},
        luma: { sourceCatalog },
        nvapi: { sourceCatalog: {} },
        optiscaler: { sourceCatalog: {} },
      }),
    );

  assert.notEqual(
    createVersion({ 'luma.game.warning': 'Original.' }),
    createVersion({ 'luma.game.warning': 'Changed.' }),
  );
  assert.notEqual(
    createVersion({ 'luma.game.warning': 'Original.' }),
    createVersion({ 'luma.game.other': 'Original.' }),
  );
});

test('generated source formatting honors file-specific oxfmt overrides', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'renderpilot-i18n-contracts-'));
  const configPath = path.join(directory, '.oxfmtrc.json');
  const filePath = path.join(directory, 'generated', 'contract.ts');

  try {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(
      configPath,
      JSON.stringify({
        singleQuote: false,
        overrides: [{ files: ['generated/**/*.ts'], options: { singleQuote: true } }],
      }),
      'utf8',
    );

    assert.equal(
      await formatGeneratedSource(filePath, 'const contract = "value";\n', configPath),
      "const contract = 'value';\n",
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('plural category parser rejects duplicates and missing other', () => {
  assert.throws(
    () => parsePluralCategories(`const PLURAL_CATEGORIES = { en: ['one', 'one'] } as const;`),
    /invalid or duplicate categories/,
  );
});

test('Luma contract enforces strict source-bound message records', () => {
  const message = {
    id: 'luma.game.warning',
    sourceText: 'Careful.',
    kind: 'warning',
    context: 'guidance.warning',
  };
  const valid = { schemaVersion: 1, messages: [message] };

  assert.deepEqual(parseLumaContract(valid).sourceCatalog, {
    'luma.game.warning': 'Careful.',
  });
  assert.throws(
    () =>
      parseLumaContract({
        ...valid,
        messages: [message, { ...message }],
      }),
    /duplicate Luma message ID/,
  );
  assert.throws(
    () =>
      parseLumaContract({
        ...valid,
        messages: [{ ...message, context: 'unknown' }],
      }),
    /invalid context/,
  );
  assert.throws(
    () =>
      parseLumaContract({
        ...valid,
        messages: [{ ...message, kind: 'engine_ini', context: 'guidance.warning' }],
      }),
    /does not match context/,
  );
  assert.throws(
    () =>
      parseLumaContract({
        ...valid,
        messages: [{ ...message, kind: 'warning', context: 'availability.blocked' }],
      }),
    /must have kind "blocked"/,
  );
  assert.throws(
    () => parseLumaContract({ ...valid, messages: [{ ...message, unexpected: true }] }),
    /unknown field/,
  );
  assert.throws(
    () => parseLumaContract({ ...valid, messages: [{ ...message, sourceText: 'Value {name}' }] }),
    /must not contain placeholders/,
  );
});

test('Luma contract exposes only reviewed stable guidance tuples', async () => {
  const source = await readFile(
    new URL('../ui/src/shared/i18n/messages/overrides/luma/source.generated.json', import.meta.url),
    'utf8',
  );
  const contract = parseLumaContract(parseJsonSource(source));

  assert.ok(Object.keys(contract.sourceCatalog).length > 0);
  assert.equal(contract.contexts['luma.ace-combat-7.engine_ini'], 'guidance.engine_ini');
});

test('OptiScaler contract rejects duplicate identifiers, invalid kinds, unknown keys, and placeholders', () => {
  const message = {
    id: 'optiscaler-game-restart',
    sourceText: 'Restart the game.',
    kind: 'compatibility',
    context: 'compatibility',
  };
  const valid = { schemaVersion: 1, messages: [message] };

  assert.deepEqual(parseOptiscalerContract(valid).sourceCatalog, {
    'optiscaler-game-restart': 'Restart the game.',
  });
  assert.throws(
    () =>
      parseOptiscalerContract({
        ...valid,
        messages: [message, { ...message }],
      }),
    /invalid or duplicate OptiScaler message id/,
  );
  assert.throws(
    () =>
      parseOptiscalerContract({
        ...valid,
        messages: [{ ...message, id: 'INVALID_UPPERCASE_ID' }],
      }),
    /invalid or duplicate OptiScaler message id/,
  );
  assert.throws(
    () =>
      parseOptiscalerContract({
        ...valid,
        messages: [{ ...message, kind: 'unknown', context: 'unknown' }],
      }),
    /invalid kind\/context/,
  );
  assert.throws(
    () =>
      parseOptiscalerContract({
        ...valid,
        messages: [{ ...message, kind: 'compatibility', context: 'game_setting' }],
      }),
    /invalid kind\/context/,
  );
  assert.throws(
    () => parseOptiscalerContract({ ...valid, messages: [{ ...message, unexpected: true }] }),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseOptiscalerContract({
        ...valid,
        messages: [{ ...message, sourceText: 'Value {name}' }],
      }),
    /must not contain placeholders/,
  );
  assert.throws(
    () => parseOptiscalerContract({ schemaVersion: 2, messages: [message] }),
    /unsupported schemaVersion/,
  );
  assert.throws(
    () => parseOptiscalerContract({ schemaVersion: 1, messages: [] }),
    /must be a non-empty array/,
  );
});

test('OptiScaler contract exposes only reviewed stable guidance tuples', async () => {
  const source = await readFile(
    new URL(
      '../ui/src/shared/i18n/messages/overrides/optiscaler/source.generated.json',
      import.meta.url,
    ),
    'utf8',
  );
  const contract = parseOptiscalerContract(parseJsonSource(source));
  const keys = Object.keys(contract.sourceCatalog);

  assert.ok(keys.length > 0);
  assert.ok(keys.every((key) => /^optiscaler-[a-z0-9-]+$/u.test(key)));
  assert.ok(
    keys.every((key) => ['compatibility', 'game_setting'].includes(contract.contexts[key])),
  );
  assert.equal(contract.contexts['optiscaler-jedi-survivor-restart'], 'compatibility');
  assert.equal(contract.contexts['optiscaler-gothic-1-remake-sharpening'], 'game_setting');
  assert.equal(
    contract.sourceCatalog['optiscaler-jedi-survivor-restart'],
    'If DLSS is unavailable after changing OptiScaler settings, restart the game.',
  );
});

test('RenoDX contract rejects duplicate identifiers, invalid kinds, unknown keys, and placeholders', () => {
  const message = {
    id: 'renodx.game.warning',
    sourceText: 'Careful.',
    kind: 'warning',
    context: 'guidance.warning',
  };
  const valid = { schemaVersion: 1, messages: [message] };

  assert.throws(
    () => parseRenodxContract({ ...valid, messages: [message, message] }),
    /duplicate RenoDX message ID/,
  );
  for (const badId of ['bad_id', 'renodx..bad', 'renodx.bad.', 'renodx.bad..segment']) {
    assert.throws(
      () =>
        parseRenodxContract({
          ...valid,
          messages: [{ ...message, id: badId }],
        }),
      /invalid message ID/,
    );
  }
  assert.throws(
    () =>
      parseRenodxContract({
        ...valid,
        messages: [{ ...message, kind: 'unknown', context: 'guidance.unknown' }],
      }),
    /invalid kind/,
  );
  assert.throws(
    () =>
      parseRenodxContract({
        ...valid,
        messages: [{ ...message, kind: 'banana', context: 'guidance.banana' }],
      }),
    /invalid kind/,
  );
  assert.throws(
    () =>
      parseRenodxContract({
        ...valid,
        messages: [{ ...message, kind: 'warning', context: 'invalid_context' }],
      }),
    /invalid context/,
  );
  assert.throws(
    () =>
      parseRenodxContract({
        ...valid,
        messages: [{ ...message, kind: 'warning', context: 'guidance.compatibility' }],
      }),
    /does not match context/,
  );
  assert.throws(
    () => parseRenodxContract({ ...valid, messages: [{ ...message, unexpected: true }] }),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseRenodxContract({
        ...valid,
        messages: [{ ...message, sourceText: 'Value {name}' }],
      }),
    /must not contain placeholders/,
  );
  assert.throws(
    () => parseRenodxContract({ schemaVersion: 2, messages: [message] }),
    /unsupported schemaVersion/,
  );
  assert.throws(
    () => parseRenodxContract({ schemaVersion: 1, messages: [] }),
    /must contain at least one message/,
  );
});

test('RenoDX contract exposes only reviewed stable guidance tuples', async () => {
  const source = await readFile(
    new URL(
      '../ui/src/shared/i18n/messages/overrides/renodx/source.generated.json',
      import.meta.url,
    ),
    'utf8',
  );
  const contract = parseRenodxContract(parseJsonSource(source));
  const keys = Object.keys(contract.sourceCatalog);

  assert.ok(keys.length > 0);
  assert.ok(keys.every((key) => /^renodx\.[a-z0-9_.-]+$/.test(key)));
  assert.ok(
    keys.every((key) =>
      [
        'guidance.engine_ini',
        'guidance.compatibility',
        'guidance.warning',
        'guidance.external_tool',
        'guidance.game_setting',
        'guidance.addon_setting',
      ].includes(contract.contexts[key]),
    ),
  );
  assert.equal(contract.contexts['renodx.black_myth_wukong.hdr'], 'guidance.engine_ini');
  assert.equal(
    contract.sourceCatalog['renodx.black_myth_wukong.hdr'],
    'In Engine.ini, add this setting for the UE Extended HDR path.',
  );
});

test('NVAPI contract rejects duplicate identifiers, invalid shapes, and placeholders', () => {
  assert.throws(
    () =>
      parseNvapiContract({
        schema_version: 1,
        settings: [
          {
            key: 'preset',
            family: 'sr',
            label: 'Preset',
            values: [
              { wire: 'a', label: 'A' },
              { wire: 'a', label: 'Duplicate' },
            ],
          },
        ],
      }),
    /invalid or duplicate wire value/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        schema_version: 1,
        settings: [
          { key: 'preset', family: 'sr', label: 'Preset', values: { wire: 'not-an-array' } },
        ],
      }),
    /values must be an array/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        schema_version: 1,
        settings: [{ key: 'preset', family: 'sr', label: 'Preset {bad-name}' }],
      }),
    /dlss_settings\.json: nvapi\.preset\.label contains invalid placeholder syntax/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        schema_version: 1,
        settings: [{ key: 'preset', family: 'sr', label: 'Preset {name}' }],
      }),
    /must not contain placeholders/,
  );
});

test('static, Luma, and NVAPI message key spaces may not overlap', () => {
  assert.throws(
    () =>
      validateExternalCatalogBoundaries(
        { 'luma.game.warning': { kind: 'string', placeholders: [] } },
        { sourceCatalog: { 'luma.game.warning': 'Warning.' } },
        { sourceCatalog: {} },
        { sourceCatalog: {} },
      ),
    /shared by English and Luma/,
  );
  assert.throws(
    () =>
      validateExternalCatalogBoundaries(
        {},
        { sourceCatalog: { 'external.same': 'Luma.' } },
        { sourceCatalog: { 'external.same': 'NVAPI.' } },
        { sourceCatalog: {} },
      ),
    /shared by Luma and NVAPI/,
  );
});

test('editorial policy rejects malformed and stale machine-readable rules', async () => {
  const [policyText, englishText, nvapiText] = await Promise.all([
    readFile(new URL('../data/i18n-editorial-policy.json', import.meta.url), 'utf8'),
    readFile(new URL('../ui/src/shared/i18n/messages/en.ts', import.meta.url), 'utf8'),
    readFile(
      new URL(
        '../../../crates/renderpilot-orchestration/src/dlss/bundled/dlss_settings.json',
        import.meta.url,
      ),
      'utf8',
    ),
  ]);
  const policy = parseJsonSource(policyText);
  const dependencies = {
    english: parseEnglishContract(englishText),
    nvapi: { sourceCatalog: parseNvapiContract(parseJsonSource(nvapiText)) },
  };
  const invalidPolicy = (mutate) => {
    const value = structuredClone(policy);
    mutate(value);
    return value;
  };

  assert.equal(validateEditorialPolicy(policy, dependencies), policy);
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => (value.schemaVersion = 99)),
        dependencies,
      ),
    /unsupported schemaVersion 99/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => (value.nvidiaSources.ru = 'http://www.nvidia.com/ru-ru/')),
        dependencies,
      ),
    /must use an official HTTPS URL/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => {
          value.localeTypography.de.quotationMarks.close =
            value.localeTypography.de.quotationMarks.open;
        }),
        dependencies,
      ),
    /quotation marks are invalid/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => {
          value.localeTypography.fr.forbiddenQuoteMarks.push(
            value.localeTypography.fr.quotationMarks.open,
          );
        }),
        dependencies,
      ),
    /forbids its approved quotation marks/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => value.technicalOnlyStaticKeys.push('missing.static.key')),
        dependencies,
      ),
    /technical-only static key is not in the English catalog/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => {
          const [source] = Object.keys(value.nvapiSemanticTranslations.ru);
          delete value.nvapiSemanticTranslations.de[source];
        }),
        dependencies,
      ),
    /NVAPI semantic translations for de is missing field/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => {
          delete value.localizedUiLiterals['City Glow Effect'].ru;
        }),
        dependencies,
      ),
    /localized UI literal City Glow Effect is missing field "ru"/,
  );
  assert.throws(
    () =>
      validateEditorialPolicy(
        invalidPolicy((value) => {
          value.localizedUiLiterals['City Glow Effect'].ru = '';
        }),
        dependencies,
      ),
    /localized UI literal City Glow Effect.ru must be a non-empty string/,
  );
});
