import assert from 'node:assert/strict';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';

import {
  analyzeMessageTemplate,
  checkI18nContractOutputs,
  createI18nContractOutputs,
  formatGeneratedSource,
  parseAddGameWarningContract,
  parseEnglishContract,
  parseDesktopCommandErrorContract,
  parseLumaContract,
  parseNvapiContract,
  parsePluralCategories,
} from './i18n-contracts.mjs';
import { parseJsonSource } from './i18n-contracts/parser.mjs';
import { PLACEHOLDER_CONTRACT_CASES } from '../ui/src/shared/i18n/messages/placeholder-contract-cases.ts';

const EXPECTED_CONTRACT_VERSION =
  'i18n-v1:5352aae56d869c0e279987a232fa42b7fc7cdf0b55cf326c1eba2c3d181e611a';

test('contract generation is deterministic and committed outputs are current', async () => {
  const first = await createI18nContractOutputs();
  const second = await createI18nContractOutputs();

  assert.deepEqual([...first], [...second]);
  assert.deepEqual(await checkI18nContractOutputs(first), []);
  assert.equal(first.size, 5);
  for (const source of first.values()) {
    assert.match(source, /^\/\/ This file is generated by `pnpm i18n:generate`\./);
  }
  const versionSource = first.entries().find(([file]) => file.endsWith('contract-version.ts'))?.[1];
  assert.match(versionSource, new RegExp(EXPECTED_CONTRACT_VERSION));
});

test('placeholder analyzer matches the shared contract table', () => {
  for (const fixture of PLACEHOLDER_CONTRACT_CASES) {
    assert.deepEqual(analyzeMessageTemplate(fixture.template), {
      valid: fixture.valid,
      placeholders: fixture.placeholders,
    });
  }
});

test('English contract parser rejects malformed tagged messages', () => {
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: plural('count', { one: '{count} item' }),
        });
      `),
    /plural branches must be exactly one and other/,
  );
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: select('tone', { other: 'Default' }),
        });
      `),
    /select branches must include other and at least one named case/,
  );
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          invalid: '{valid} then {bad-name}',
        });
      `),
    /contains invalid placeholder syntax/,
  );
});

test('generator diagnostics identify the source file and message key', () => {
  assert.throws(
    () =>
      parseEnglishContract(`
        const en = defineSourceCatalog({
          'broken.message': '{valid} then {bad-name}',
        });
      `),
    /ui\/src\/shared\/i18n\/messages\/en\.ts: English message broken\.message contains invalid placeholder syntax/,
  );
});

test('source parsers reject malformed TypeScript and JSON with actionable diagnostics', () => {
  assert.throws(
    () => parseEnglishContract('const en = defineSourceCatalog({ broken: "value"; });'),
    /ui\/src\/shared\/i18n\/messages\/en\.ts: TypeScript syntax error at 1:\d+:/,
  );
  assert.throws(() => parseJsonSource('{"broken":'), /invalid JSON/);
});

test('desktop command-error manifest validates codes, references, and strict shapes', () => {
  const english = parseEnglishContract(`
    const en = defineSourceCatalog({
      'error.message': 'Failed.',
      'error.action': 'Try again.',
      'warning.count': plural('count', { one: 'One', other: '{count} items' }),
    });
  `);
  const valid = {
    schemaVersion: 1,
    commandErrors: [
      {
        code: 'operation_failed',
        rustVariant: 'OperationFailed',
        messageKey: 'error.message',
        severity: 'error',
        actions: ['retry'],
      },
    ],
    suggestedActions: [{ code: 'retry', messageKey: 'error.action' }],
  };

  assert.equal(parseDesktopCommandErrorContract(valid, english).schemaVersion, 1);
  assert.throws(
    () => parseDesktopCommandErrorContract({ ...valid, schemaVersion: 2 }, english),
    /unsupported schemaVersion/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        { ...valid, commandErrors: [...valid.commandErrors, valid.commandErrors[0]] },
        english,
      ),
    /duplicate code/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], code: `a${'b'.repeat(64)}` }],
        },
        english,
      ),
    /invalid machine code/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], rustVariant: 'invalid_variant' }],
        },
        english,
      ),
    /invalid rustVariant/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], messageKey: 'error.missing' }],
        },
        english,
      ),
    /missing English message/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          suggestedActions: [{ ...valid.suggestedActions[0], messageKey: 'error.missing' }],
        },
        english,
      ),
    /missing English message/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], actions: ['missing'] }],
        },
        english,
      ),
    /unknown suggested action/,
  );
  assert.throws(
    () => parseDesktopCommandErrorContract({ ...valid, unexpected: true }, english),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [{ ...valid.commandErrors[0], recoveryBundlePath: false }],
        },
        english,
      ),
    /must be true when present/,
  );
  assert.throws(
    () =>
      parseDesktopCommandErrorContract(
        {
          ...valid,
          commandErrors: [
            { ...valid.commandErrors[0], severity: 'warning', recoveryBundlePath: true },
          ],
        },
        english,
      ),
    /exposes a recovery path but is not an error/,
  );
});

test('add-game warning manifest validates references, parameters, and strict shapes', () => {
  const english = parseEnglishContract(`
    const en = defineSourceCatalog({
      'warning.count': plural('count', { one: 'One', other: '{count} items' }),
    });
  `);
  const valid = {
    schemaVersion: 1,
    addGameWarnings: [
      {
        code: 'items_found',
        messageKey: 'warning.count',
        parameters: { count: 'positive_integer' },
      },
    ],
  };

  assert.equal(parseAddGameWarningContract(valid, english).schemaVersion, 1);
  assert.throws(
    () => parseAddGameWarningContract({ ...valid, unexpected: true }, english),
    /unknown field/,
  );
  assert.throws(
    () =>
      parseAddGameWarningContract(
        {
          ...valid,
          addGameWarnings: [
            { ...valid.addGameWarnings[0], parameters: { path: 'non_blank_string' } },
          ],
        },
        english,
      ),
    /do not match English message/,
  );
  assert.throws(
    () =>
      parseAddGameWarningContract(
        {
          ...valid,
          addGameWarnings: [
            { ...valid.addGameWarnings[0], parameters: { count: 'arbitrary_text' } },
          ],
        },
        english,
      ),
    /invalid type/,
  );
});

test('stale detection reports missing and mismatched generated outputs', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'renderpilot-i18n-stale-'));
  const missingPath = path.join(directory, 'missing.ts');
  const mismatchedPath = path.join(directory, 'mismatched.ts');

  try {
    await writeFile(mismatchedPath, 'actual\n', 'utf8');
    const stale = await checkI18nContractOutputs(
      new Map([
        [missingPath, 'expected\n'],
        [mismatchedPath, 'expected\n'],
      ]),
    );

    assert.equal(stale.length, 2);
    assert.equal(stale[0].endsWith('missing.ts'), true);
    assert.equal(stale[1].endsWith('mismatched.ts'), true);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('contract records use locale-independent ordinal key order', () => {
  const contract = parseEnglishContract(`
    const en = defineSourceCatalog({
      'a_b': 'underscore',
      'a.b': 'dot',
      'a-b': 'dash',
    });
  `);

  assert.deepEqual(Object.keys(contract), ['a-b', 'a.b', 'a_b']);
});

test('generated source formatting honors file-specific oxfmt overrides', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'renderpilot-i18n-contracts-'));
  const configPath = path.join(directory, '.oxfmtrc.json');
  const filePath = path.join(directory, 'generated', 'contract.ts');

  try {
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(
      configPath,
      JSON.stringify({
        singleQuote: false,
        overrides: [{ files: ['generated/**/*.ts'], options: { singleQuote: true } }],
      }),
      'utf8',
    );

    assert.equal(
      await formatGeneratedSource(filePath, 'const contract = "value";\n', configPath),
      "const contract = 'value';\n",
    );
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
});

test('plural category parser rejects duplicates and missing other', () => {
  assert.throws(
    () => parsePluralCategories(`const PLURAL_CATEGORIES = { en: ['one', 'one'] } as const;`),
    /invalid or duplicate categories/,
  );
});

test('dynamic registry parsers reject duplicate source identifiers', () => {
  assert.throws(
    () =>
      parseLumaContract({
        bundledDlss: ['luma.game.bundled_dlss'],
        reservedDlss: ['luma.game.bundled_dlss'],
      }),
    /duplicate Luma message ID/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        settings: [
          {
            key: 'preset',
            label: 'Preset',
            values: [
              { wire: 'a', label: 'A' },
              { wire: 'a', label: 'Duplicate' },
            ],
          },
        ],
      }),
    /invalid or duplicate wire value/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        settings: [{ key: 'preset', label: 'Preset', values: { wire: 'not-an-array' } }],
      }),
    /values must be an array/,
  );
  assert.throws(
    () =>
      parseNvapiContract({
        settings: [{ key: 'preset', label: 'Preset {bad-name}' }],
      }),
    /dlss_settings\.json: nvapi\.preset\.label contains invalid placeholder syntax/,
  );
});
