const GENERATED_HEADER =
  '// This file is generated by `pnpm i18n:generate`. Do not edit it manually.\n';

export function renderNvapiContract(sourceMessages, verbatimValues, settingCount) {
  const verbatimTranslations = Object.fromEntries(verbatimValues.map((value) => [value, value]));
  return `${GENERATED_HEADER}
export const NVAPI_SOURCE_CATALOG = ${JSON.stringify(sourceMessages, null, 2)} as const;
export const NVAPI_VERBATIM_TRANSLATIONS = ${JSON.stringify(verbatimTranslations, null, 2)} as const;
export const NVAPI_SETTING_COUNT = ${JSON.stringify(settingCount)} as const;

export type NvapiSourceCatalog = typeof NVAPI_SOURCE_CATALOG;
export type NvapiMessageKey = keyof NvapiSourceCatalog;
export type NvapiSourceText = NvapiSourceCatalog[NvapiMessageKey];
export type NvapiVerbatimSourceText = keyof typeof NVAPI_VERBATIM_TRANSLATIONS;
export type NvapiLocalizedSourceText = Exclude<NvapiSourceText, NvapiVerbatimSourceText>;
export type NvapiTranslations = Readonly<Record<NvapiLocalizedSourceText, string>>;
export type ExpandedNvapiCatalog<Translations extends NvapiTranslations> = Readonly<{
  [Key in NvapiMessageKey]: NvapiSourceCatalog[Key] extends NvapiVerbatimSourceText
    ? NvapiSourceCatalog[Key]
    : Translations[Extract<NvapiSourceCatalog[Key], NvapiLocalizedSourceText>];
}>;

export function expandNvapiTranslations<const Translations extends NvapiTranslations>(
  localized: Translations,
): ExpandedNvapiCatalog<Translations> {
  return Object.fromEntries(
    Object.entries(NVAPI_SOURCE_CATALOG).map(([key, source]) => [
      key,
      Object.hasOwn(NVAPI_VERBATIM_TRANSLATIONS, source)
        ? source
        : localized[source as NvapiLocalizedSourceText],
    ]),
  ) as ExpandedNvapiCatalog<Translations>;
}
`;
}

export function renderLumaContract({ groups, sourceCatalog, contexts }) {
  return `${GENERATED_HEADER}
export const LUMA_MESSAGE_GROUPS = ${JSON.stringify(groups, null, 2)} as const;
export const LUMA_SOURCE_CATALOG = ${JSON.stringify(sourceCatalog, null, 2)} as const;
export const LUMA_MESSAGE_CONTEXTS = ${JSON.stringify(contexts, null, 2)} as const;

export type LumaMessagePhrase = keyof typeof LUMA_MESSAGE_GROUPS;
export type LumaMessageTranslations = Readonly<Record<LumaMessagePhrase, string>>;
export type LumaMessageKey =
  (typeof LUMA_MESSAGE_GROUPS)[LumaMessagePhrase][number];
export type LumaSourceCatalog = typeof LUMA_SOURCE_CATALOG;

type LumaMessagePhraseFor<Key extends LumaMessageKey> = {
  [Phrase in LumaMessagePhrase]: Key extends (typeof LUMA_MESSAGE_GROUPS)[Phrase][number]
    ? Phrase
    : never;
}[LumaMessagePhrase];

export type ExpandedLumaCatalog<
  Translations extends LumaMessageTranslations,
> = Readonly<{
  [Key in LumaMessageKey]: Translations[LumaMessagePhraseFor<Key>];
}>;

export function expandLumaTranslations<
  const Translations extends LumaMessageTranslations,
>(localized: Translations): ExpandedLumaCatalog<Translations> {
  const expanded: Partial<Record<LumaMessageKey, string>> = {};

  for (const [phrase, ids] of Object.entries(LUMA_MESSAGE_GROUPS) as [
    LumaMessagePhrase,
    readonly LumaMessageKey[],
  ][]) {
    for (const id of ids) {
      if (Object.hasOwn(expanded, id)) {
        throw new Error(\`Duplicate Luma message ID: \${id}\`);
      }
      expanded[id] = localized[phrase];
    }
  }

  return expanded as ExpandedLumaCatalog<Translations>;
}
`;
}

export function renderContractVersion(version) {
  return `${GENERATED_HEADER}
export const MESSAGE_CONTRACT_VERSION = ${JSON.stringify(version)} as const;
`;
}

export function renderDesktopCommandErrorContract(contract) {
  const frontendContract = {
    schemaVersion: contract.schemaVersion,
    commandErrors: Object.fromEntries(
      Object.entries(contract.commandErrors).map(([code, spec]) => [
        code,
        {
          messageKey: spec.messageKey,
          severity: spec.severity,
          actions: spec.actions,
          reasonCodes: spec.reasonCodes,
          recoveryBundlePath: spec.recoveryBundlePath,
        },
      ]),
    ),
    suggestedActions: contract.suggestedActions,
  };

  return `${GENERATED_HEADER}
export const DESKTOP_COMMAND_ERROR_CONTRACT = ${JSON.stringify(frontendContract, null, 2)} as const;

export const COMMAND_ERROR_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.commandErrors;
export const SUGGESTED_ACTION_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.suggestedActions;

export type CommandErrorCode = keyof typeof COMMAND_ERROR_CONTRACT;
export type SuggestedActionCode = keyof typeof SUGGESTED_ACTION_CONTRACT;
`;
}

export function renderAddGameWarningContract(contract) {
  return `${GENERATED_HEADER}
export const ADD_GAME_WARNING_CONTRACT = ${JSON.stringify(contract.addGameWarnings, null, 2)} as const;

export type AddGameWarningCode = keyof typeof ADD_GAME_WARNING_CONTRACT;
`;
}
