const GENERATED_HEADER =
  '// This file is generated by `pnpm i18n:generate`. Do not edit it manually.\n';

function typeProperty(key, valueType) {
  return `  readonly ${JSON.stringify(key)}: ${valueType};`;
}

export function renderNvapiContract(sourceMessages) {
  const properties = Object.entries(sourceMessages)
    .map(([key, value]) => typeProperty(key, JSON.stringify(value)))
    .join('\n');
  return `${GENERATED_HEADER}
export type NvapiSourceCatalog = Readonly<{
${properties}
}>;

export type NvapiMessageKey = keyof NvapiSourceCatalog;
`;
}

export function renderLumaContract({ groups }) {
  return `${GENERATED_HEADER}
export const LUMA_GUIDANCE_GROUPS = ${JSON.stringify(groups, null, 2)} as const;

export type LumaGuidancePhrase = keyof typeof LUMA_GUIDANCE_GROUPS;
export type LumaGuidanceTranslations = Readonly<Record<LumaGuidancePhrase, string>>;
export type LumaGuidanceKey =
  (typeof LUMA_GUIDANCE_GROUPS)[LumaGuidancePhrase][number];
export type LumaSourceCatalog = Readonly<Record<LumaGuidanceKey, ''>>;

type LumaGuidancePhraseFor<Key extends LumaGuidanceKey> = {
  [Phrase in LumaGuidancePhrase]: Key extends (typeof LUMA_GUIDANCE_GROUPS)[Phrase][number]
    ? Phrase
    : never;
}[LumaGuidancePhrase];

export type ExpandedLumaGuidanceCatalog<
  Translations extends LumaGuidanceTranslations,
> = Readonly<{
  [Key in LumaGuidanceKey]: Translations[LumaGuidancePhraseFor<Key>];
}>;

export function expandLumaGuidanceTranslations<
  const Translations extends LumaGuidanceTranslations,
>(localized: Translations): ExpandedLumaGuidanceCatalog<Translations> {
  const expanded: Partial<Record<LumaGuidanceKey, string>> = {};

  for (const [phrase, ids] of Object.entries(LUMA_GUIDANCE_GROUPS) as [
    LumaGuidancePhrase,
    readonly LumaGuidanceKey[],
  ][]) {
    for (const id of ids) {
      if (Object.prototype.hasOwnProperty.call(expanded, id)) {
        throw new Error(\`Duplicate Luma guidance ID: \${id}\`);
      }
      expanded[id] = localized[phrase];
    }
  }

  return expanded as ExpandedLumaGuidanceCatalog<Translations>;
}
`;
}

export function renderContractVersion(version) {
  return `${GENERATED_HEADER}
export const MESSAGE_CONTRACT_VERSION = ${JSON.stringify(version)} as const;
`;
}

export function renderDesktopCommandErrorContract(contract) {
  const frontendContract = {
    schemaVersion: contract.schemaVersion,
    commandErrors: Object.fromEntries(
      Object.entries(contract.commandErrors).map(([code, spec]) => [
        code,
        {
          messageKey: spec.messageKey,
          severity: spec.severity,
          actions: spec.actions,
          reasonCodes: spec.reasonCodes,
          recoveryBundlePath: spec.recoveryBundlePath,
        },
      ]),
    ),
    suggestedActions: contract.suggestedActions,
  };

  return `${GENERATED_HEADER}
export const DESKTOP_COMMAND_ERROR_CONTRACT = ${JSON.stringify(frontendContract, null, 2)} as const;

export const COMMAND_ERROR_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.commandErrors;
export const SUGGESTED_ACTION_CONTRACT = DESKTOP_COMMAND_ERROR_CONTRACT.suggestedActions;

export type CommandErrorCode = keyof typeof COMMAND_ERROR_CONTRACT;
export type SuggestedActionCode = keyof typeof SUGGESTED_ACTION_CONTRACT;
`;
}

export function renderAddGameWarningContract(contract) {
  return `${GENERATED_HEADER}
export const ADD_GAME_WARNING_CONTRACT = ${JSON.stringify(contract.addGameWarnings, null, 2)} as const;

export type AddGameWarningCode = keyof typeof ADD_GAME_WARNING_CONTRACT;
`;
}
