/**
 * Wire-level Data Transfer Objects (DTOs) strictly mirroring the Rust backend structures
 * defined in `crates/renderpilot-cli/src/desktop/nvapi.rs`.
 *
 * To ensure infallible serialization boundaries, field names within these interfaces
 * must exactly match the JSON keys generated by the backend's `serde` implementation.
 */

export type SettingDescriptor = {
  setting_key: string;
  setting_label: string;
  value_type: string;
  dll_kind: string | null;
  family: string | null;
};

/** Grouping family of a DLSS setting, used for UI sectioning. */
export type SettingFamily = 'sr' | 'fg' | 'rr';

export type ExecutableCandidate = {
  relative_path: string;
  file_name: string;
  absolute_path: string;
  size_bytes: number;
  depth: number;
  rank_score: number;
  rejection: string | null;
  rejection_token: string | null;
};

export type ValueOption = {
  wire: string;
  label: string;
  supported: boolean;
};

export type ValueDescriptor = {
  wire: string;
  label: string;
  dword: number;
};

export type BaselineDto = {
  wire: string | null;
  label: string | null;
  dword: number;
  was_predefined: boolean;
  captured_at: number;
  captured_exe: string;
};

export type DllInfoDto = {
  kind: string;
  version: string;
  path: string;
  manifest_label: string | null;
};

export type NvapiWarning =
  | 'noDll'
  | 'noManifest'
  | 'noExecutable'
  | 'nvapiUnavailable'
  | 'nvapiInitFailed'
  | 'drsFailed';

export type SettingStateResponse = {
  setting_key: string;
  setting_label: string;
  value_type: string;
  family: string | null;
  category: string | null;
  description: string | null;
  min_driver: string | null;
  current: ValueDescriptor;
  predefined: ValueDescriptor | null;
  baseline: BaselineDto | null;
  is_current_predefined: boolean;
  is_modified_outside_renderpilot: boolean;
  effective_exe: string | null;
  effective_exe_source: 'auto' | 'override' | null;
  has_profile_for_exe: boolean;
  nvapi_available: boolean;
  available_values: ValueOption[];
  dll_info: DllInfoDto | null;
  warnings: NvapiWarning[];
};

/**
 * State of the system-wide NVIDIA DLSS indicator overlay. This is a single
 * machine-wide registry toggle (read by NGX for every DLSS title), so it is
 * global rather than per-game. `supported` is `false` on non-Windows platforms.
 */
export type DlssIndicatorState = {
  enabled: boolean;
  supported: boolean;
};
