// This file is generated by `pnpm i18n:generate`. Do not edit it manually.

export const OPTISCALER_SOURCE_CATALOG = {
  'optiscaler-1666-amsterdam-fsr4-color-space':
    'When using FSR 4 through DLSS or XeSS, select the Non-Linear input color space to avoid black screens and flicker.',
  'optiscaler-akimbot-taa-dlss': 'Enable both TAA and DLSS in the game settings.',
  'optiscaler-alone-in-the-dark-2024-dx12-dlss':
    'In the game settings, change the DLSS mode and apply the change.',
  'optiscaler-apocalypse-2-0-display-res-mv':
    'Disable Display Res.MV in the game settings to fix shimmer.',
  'optiscaler-assassins-creed-origins-dlss-mod':
    'A third-party DLSS mod is required for this game to work with OptiScaler.',
  'optiscaler-assassins-creed-shadows-overlay-hdr':
    'Disable the Ubisoft Connect in-game overlay and HDR while using OptiScaler to avoid severe ghosting.',
  'optiscaler-assetto-corsa-evo-fsr4-autoexposure':
    'When using FSR 4 with DLSS input, enable AutoExposure.',
  'optiscaler-asterigos-fsr2-detection':
    'Change the in-game FSR quality setting once so OptiScaler can detect the FSR 2 input.',
  'optiscaler-automate-it-fsr-detection':
    'Change the in-game FSR setting once so OptiScaler can detect the FSR input.',
  'optiscaler-batora-lost-haven-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-blades-of-fire-overlay-keyboard':
    'Use the keyboard to navigate the OptiScaler overlay; mouse input is unavailable.',
  'optiscaler-bloodstained-frame-smoothing':
    'Disable Frame Smoothing in the game settings to remove the frame-rate cap.',
  'optiscaler-blue-protocol-star-resonance-shaders':
    'Complete shader compilation before selecting FSR 4 to avoid a crash.',
  'optiscaler-bright-memory-dx12-ray-tracing':
    'To use a DLSS input, enable ray tracing and NVIDIA spoofing.',
  'optiscaler-brothers-remake-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix screen flicker.',
  'optiscaler-car-mechanic-simulator-2026-single-player-demo-fsr3-mode':
    'FSR 3 mode is unavailable.',
  'optiscaler-chernobylite-2-cinematic-reflections':
    'If surfaces sparkle, set Cinematic Reflections to Ultra or lower.',
  'optiscaler-chionophile-dx12': 'DirectX 11 can shimmer.',
  'optiscaler-chip-n-clawz-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flicker in cutscenes.',
  'optiscaler-cions-of-vega-dx12': 'DirectX 11 can shimmer.',
  'optiscaler-crash-bandicoot-4-antialiasing':
    'Set anti-aliasing quality to at least Medium (2×) in the game settings.',
  'optiscaler-crimson-oath-fsr4-color-space':
    'When using FSR 4 with XeSS input, select the Non-Linear input color space.',
  'optiscaler-curse-of-the-abandoned-floor-upscale-ratio':
    "If the upscaling preset changes after restart, use OptiScaler's Upscale Ratio Override to select it.",
  'optiscaler-cyberpunk-fsr4-input':
    'You can use FSR 4 as an OptiScaler input regardless of your GPU.',
  'optiscaler-daemon-x-machina-titanic-scion-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix screen flicker.',
  'optiscaler-darksiders-3-antialiasing': 'Set anti-aliasing quality to Epic in the game settings.',
  'optiscaler-dawn-break-demo-dx12-motion-blur-color-space':
    'Disable motion blur. With FSR 4, select Non-Linear PQ Input to prevent flicker.',
  'optiscaler-ddod-3d-resolution':
    "Use the game's 3D Resolution slider to change the upscaling preset.",
  'optiscaler-dead-rising-deluxe-remaster-root-signature':
    'If DLSS input has graphical issues, enable Restore Compute Root Signature in OptiScaler.',
  'optiscaler-dead-space-2023-motion-blur':
    "Disable motion blur in the game settings to reduce ghosting around Isaac's head.",
  'optiscaler-dead-take-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flashing graphics.',
  'optiscaler-deadzone-rogue-frame-generation':
    'If frame generation stops working, re-enable DLSS-FG in the game settings.',
  'optiscaler-death-stranding-2-xess-input': 'Use XeSS input to avoid shimmer.',
  'optiscaler-deconstruction-simulator-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flashing graphics.',
  'optiscaler-deliver-us-mars-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-deliver-us-the-moon-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-destroy-all-humans-2-reprobed-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-devil-may-cry-5-reframework-pdperfplugin':
    'REFramework (pd-upscaler branch) and PDPerfPlugin are required for this game to work.',
  'optiscaler-diablo-iv-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-dream-eaters-fsr4-color-space':
    'When using FSR 4 with DLSS input, select the Non-Linear input color space.',
  'optiscaler-duskfade-demo-fsr-frame-generation':
    'FSR Frame Generation is unavailable in this game.',
  'optiscaler-echoes-of-the-end-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix screen flicker.',
  'optiscaler-elden-ring-erss-fg-mod':
    'The ERSS-FG mod is required as a basis for upscaling and Frame Generation.',
  'optiscaler-escape-simulator-2-demo-dynamic-resolution':
    "Select DLSS in the Dynamic Resolution setting. Use OptiScaler's scale override to choose a different upscaling preset.",
  'optiscaler-evil-west-dx12': 'DirectX 11 can have lower performance and severe shimmer.',
  'optiscaler-f1-22-dlss-quality':
    'Keep DLSS at Quality; changing it can crash the game. Change the scale ratio in OptiScaler instead.',
  'optiscaler-final-fantasy-xvi-fsr4-color-space':
    'If image quality is poor with FSR 4, try selecting the Non-Linear PQ input color space.',
  'optiscaler-finnish-cottage-simulator-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flashing graphics.',
  'optiscaler-five-nights-at-freddys-security-breach-dlss':
    'DLSS is enabled by default and cannot be disabled in the game settings.',
  'optiscaler-fixforce-frame-generation':
    'FSR 3.1 frame generation input is unsupported. Use DLSSG through the Streamline input, or native XeFG/FSR frame generation.',
  'optiscaler-flipscapes-input-detection':
    'Change the in-game FSR setting so OptiScaler can detect the FSR 3.1 input. If using DLSS input, restart the game after selecting DLSS.',
  'optiscaler-forgive-me-father-2-dx12-fsr4':
    'With FSR 4, select Non-Linear sRGB Input if the screen flickers.',
  'optiscaler-frostpunk-2-fsr4-color-space':
    'For FSR 4, select the Non-Linear sRGB input color space for better image quality.',
  'optiscaler-frozenheim-dx12': "Use the game's DX12 mode.",
  'optiscaler-funko-fusion-fsr4-color-space':
    'Use FSR input. If FSR 4 flickers at the Balanced preset, select the Non-Linear sRGB input color space.',
  'optiscaler-ghost-recon-wildlands-dlss-mod':
    'A third-party DLSS mod is required for this game to work with OptiScaler.',
  'optiscaler-ghostrunner-2-dx12-performance':
    'For better performance, prefer FSR or XeSS mode, or use OptiPatcher.',
  'optiscaler-gothic-1-remake-sharpening':
    'Reduce the in-game sharpening setting if the image looks oversharpened.',
  'optiscaler-greedland-input-reload':
    'After selecting DLSS input, restart the game so OptiScaler can detect it. FSR 3 input does not require a restart.',
  'optiscaler-grid-legends-antialiasing': 'If the image looks blurry, try disabling TAA.',
  'optiscaler-gta-iii-definitive-city-glow': 'Disable City Glow Effect in the game settings.',
  'optiscaler-gta-san-andreas-definitive-city-glow':
    'Disable City Glow Effect in the game settings.',
  'optiscaler-gta-vice-city-definitive-city-glow': 'Disable City Glow Effect in the game settings.',
  'optiscaler-hello-neighbor-2-dlss':
    'DLSS input is available in the OptiScaler menu even though no DLSS option is shown in the game settings.',
  'optiscaler-highrise-city-dx12': "Use the game's DX12 mode.",
  'optiscaler-hold-your-own-dlss': 'DLSS is enabled by default.',
  'optiscaler-immortals-of-aveum-upscaler-reset':
    'After loading a new level, reselect the desired upscaler if it was reset.',
  'optiscaler-influx-redux-fsr3-water-flicker':
    'FSR 3 Quality can cause flashing lights on water. Use Balanced or Performance, or select DLSS.',
  'optiscaler-jedi-survivor-restart':
    'If DLSS is unavailable after changing OptiScaler settings, restart the game.',
  'optiscaler-jedi-survivor-windowed': 'Use borderless windowed mode for reliable overlay access.',
  'optiscaler-judgment-input': 'Use DLSS input; FSR 2.1 and XeSS inputs are unavailable.',
  'optiscaler-kiborg-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flickering.',
  'optiscaler-kiln-temporal-upscaling':
    'Use the in-game Temporal Upscaling slider to choose the upscaling preset.',
  'optiscaler-kunitsu-gami-root-signature':
    'To fix graphics corruption, enable Restore Compute Root Signature in Advanced Settings > Root Signatures.',
  'optiscaler-land-of-the-vikings-dx12-model-5': 'Use Model 5 to reduce shimmer on trees.',
  'optiscaler-lego-batman-xefg': 'Disable XeFG in the game settings to avoid a launch failure.',
  'optiscaler-liminalcore-fsr31-crash-fix':
    'Enable the FSR 3.1 input crash fix before using FSR input.',
  'optiscaler-lost-judgment-input': 'Select XeSS in the game settings; DLSS input is unavailable.',
  'optiscaler-lost-records-input': 'Use DLSS input; FSR 3 input is unavailable.',
  'optiscaler-lumina-veil-frame-generation':
    'FSR frame generation can crash the game at launch. Use XeFG instead.',
  'optiscaler-lunar-eclipse-frame-generation':
    'Do not use FSR frame generation. With FSR 4 through DLSS input, select the Non-Linear input color space.',
  'optiscaler-martha-is-dead-fsr4-color-space':
    'If angled windows look pixelated with FSR 4, try the Non-Linear PQ input color space.',
  'optiscaler-metal-gear-solid-delta-dlss-quality':
    'DLSS Quality uses a 75% internal resolution and Balanced uses 67%, which is higher than expected.',
  'optiscaler-morbid-metal-dlss-restart':
    'After selecting DLSS in the game settings for the first time, restart the game if it is not detected.',
  'optiscaler-mr-photographer-dx11': 'XeSS input is unavailable in DirectX 11 mode.',
  'optiscaler-oddroom-dx12': 'If the DLSS input does not work, launch the game with -dx12.',
  'optiscaler-oddsparks-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flickering.',
  'optiscaler-onimusha-way-of-the-sword-reframework':
    'REFramework is required for this game to work.',
  'optiscaler-online-404-reselect-upscaler':
    "After each launch, select TSR, then select DLSS again in the game's graphics settings.",
  'optiscaler-pax-autocratica-prologue-dlss-input': 'Use DLSS because FSR inputs are unavailable.',
  'optiscaler-payday-3-fsr-input': 'Avoid FSR 3 inputs because they can crash the game.',
  'optiscaler-planet-coaster-2-dlss-input': 'Use DLSS because FSR 3 inputs are unavailable.',
  'optiscaler-polaris-demo-inputs':
    'DLSS and DLSS Frame Generation inputs are unavailable. FSR 3.1 Frame Generation can crash with OptiScaler 0.9.1.',
  'optiscaler-project-songbird-teaser-faceless-dynamic-resolution':
    'Enable dynamic resolution in the game settings to use DLSS. FSR inputs are unavailable.',
  'optiscaler-project-station-demo-dx12':
    'FSR 3 input and XeSS Frame Generation output are unavailable. Do not enable Allow Async with FSR Frame Generation; it can crash the game.',
  'optiscaler-psalm-2-dlss-input':
    'Use DLSS because FSR inputs are unavailable. Do not force DirectX 12.',
  'optiscaler-psycho-fear-fsr4-input-color-space':
    'For FSR 4, select Non-Linear sRGB Input to prevent screen flickering.',
  'optiscaler-quarantine-zone-the-last-check-fsr4-input-color-space':
    'For FSR 4, select Non-Linear Color Space to prevent sky artifacts.',
  'optiscaler-raji-an-ancient-epic-dlss-input': 'Use DLSS because FSR input is not detected.',
  'optiscaler-ready-or-not-resolution-scale':
    "Use the game's resolution scale control to adjust the OptiScaler input resolution.",
  'optiscaler-realmwalker-taa-dlss': 'Enable TAA and DLSS in the game settings.',
  'optiscaler-red-dead-redemption-2-vulkan-reflex':
    'Disable NVIDIA Reflex in the game settings to reduce stuttering.',
  'optiscaler-redout-2-xess-artifacts':
    'The XeSS input can show black block artifacts in cutscenes and some levels.',
  'optiscaler-resident-evil-2-remake-reframework-upscalerbase-plugin':
    "REFramework (pd-upscaler branch) and PureDark's UpscalerBasePlugin version 1.1.2 are required for this game to work.",
  'optiscaler-resident-evil-3-remake-reframework-upscalerbase-plugin':
    "REFramework (pd-upscaler branch) and PureDark's UpscalerBasePlugin version 1.1.2 are required for this game to work.",
  'optiscaler-resident-evil-4-remake-reframework-upscalerbase-plugin':
    "REFramework (pd-upscaler branch) and PureDark's UpscalerBasePlugin version 1.1.2 are required for this game to work.",
  'optiscaler-resident-evil-7-reframework-upscalerbase-plugin':
    "REFramework (pd-upscaler branch) and PureDark's UpscalerBasePlugin version 1.1.2 are required for this game to work.",
  'optiscaler-resident-evil-requiem-reframework': 'REFramework is required for this game to work.',
  'optiscaler-riven-fsr4-non-linear-srgb-input':
    'If FSR 4 flickers, try the Non-Linear sRGB Input color space.',
  'optiscaler-robocop-rogue-city-unfinished-business-fsr4-balanced-flicker':
    'With FSR 4, DLSS Balanced can flicker. Try another preset or input; Non-Linear sRGB Input can help but may increase ghosting.',
  'optiscaler-roboquest-antialiasing':
    'Set anti-aliasing to TAA and quality to 3 in the game settings.',
  'optiscaler-romancelvania-dx12': 'DirectX 11 has lower performance.',
  'optiscaler-romeo-is-a-dead-man-anti-aliasing':
    'In the game settings, select TSR or TAA for anti-aliasing.',
  'optiscaler-saints-row-2022-dx12-fsr4':
    'Use DX12. With FSR 4, Non-Linear sRGB Input may be needed and can increase ghosting.',
  'optiscaler-scathe-dx12-fsr-input': 'FSR mode can crash the game.',
  'optiscaler-scp-secret-files-dx12':
    'Do not select an FSR 2 input; it can crash. DirectX 11 has lower performance and severe shimmer.',
  'optiscaler-sekiro-shadows-die-twice-sekirotsr-mod':
    'The SekiroTSR mod is required as a basis for DLSS inputs.',
  'optiscaler-shadow-warrior-3-dx12': 'DirectX 11 has lower performance and severe shimmer.',
  'optiscaler-shatterline-dx11-upscaler-quality':
    'In DX11, upscaler image quality can be worse than native.',
  'optiscaler-smile-protocol-demo-xefg': 'FSR Frame Generation crashes. Use XeFG instead.',
  'optiscaler-sons-of-the-forest-inventory':
    'Opening or closing the inventory can cause issues while using OptiScaler.',
  'optiscaler-soulslinger-envoy-of-death-fsr4-non-linear-srgb-input':
    'For FSR 4, select Non-Linear sRGB Input to prevent screen flicker.',
  'optiscaler-spyro-reignited-antialiasing': 'Set anti-aliasing to High TAA in the game settings.',
  'optiscaler-stalker-call-of-prypiat-enhanced-edition-dlss-input':
    'Use DLSS inputs because FSR 3.1 inputs may not upscale correctly.',
  'optiscaler-stalker-clear-sky-enhanced-edition-dlss-input':
    'Use DLSS inputs because FSR 3.1 inputs may not upscale correctly.',
  'optiscaler-stalker-shadow-of-chornobyl-enhanced-edition-dlss-input':
    'Use DLSS inputs because FSR 3.1 inputs may not upscale correctly.',
  'optiscaler-star-wars-zero-company-vendor-options':
    'Frame Generation and Low Latency options depend on the GPU vendor.',
  'optiscaler-steelrising-fsr4-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to avoid ghosting.',
  'optiscaler-stranded-alien-dawn-fsr2-input': 'FSR 2 inputs may not work.',
  'optiscaler-styx-blades-of-greed-fsr4-non-linear-srgb-input':
    'For FSR 4, select Non-Linear sRGB Input to prevent DLSS-input flicker.',
  'optiscaler-sumerian-six-fsr4-non-linear-srgb-input':
    'For FSR 4, select Non-Linear sRGB Input to prevent screen flashing.',
  'optiscaler-system-shock-remake-dx11':
    'Keep the default DirectX 11 mode. Forcing DirectX 12 with -dx12 can cause random crashes in specific areas.',
  'optiscaler-tainted-grail-dx12-skybox':
    'With FSR 4, select Non-Linear PQ Input if you encounter rare skybox issues.',
  'optiscaler-tchia-xess-corruption': 'Use DLSS inputs; XeSS can cause severe visual corruption.',
  'optiscaler-tekken-8-fsr4-artifacts':
    "When using FSR 4, some characters' hair and the second floor of DESCENT INTO SUBCONSCIOUS can show severe visual artifacts.",
  'optiscaler-tempest-rising-fsr4-non-linear-srgb-input':
    'For FSR 4, select Non-Linear sRGB Input if the screen flashes.',
  'optiscaler-terratech-legion-fsr4-non-linear-color-space':
    'FSR 3.1 inputs are unavailable. For FSR 4, select Non-Linear Color Space to avoid black screens and DLSS artifacts.',
  'optiscaler-the-alley-demo-frame-generation':
    'Enable Frame Generation after each game launch so OptiScaler can hook the input.',
  'optiscaler-the-alters-dlss-input':
    'Use DLSS input: OptiScaler does not detect the in-game FSR 3 setting.',
  'optiscaler-the-chant-fsr2-shimmer': 'Use DLSS input; FSR 2 can shimmer.',
  'optiscaler-the-hollow-complex-demo-fsr3-input': 'FSR 3 inputs are unavailable.',
  'optiscaler-the-medium-dx12': 'Run the game in DirectX 12 mode.',
  'optiscaler-the-occultist-fsr4-non-linear-srgb-input-color-space':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flicker.',
  'optiscaler-the-orville-interactive-fan-experience-dx12-launch-option':
    'Run the game in DirectX 12 mode.',
  'optiscaler-tormented-souls-2-dx11':
    'Use the default DirectX 11 mode. Forcing DirectX 12 with -dx12 crashes at startup.',
  'optiscaler-total-war-warhammer-3-warhammer3dlss-mod':
    'The Warhammer3DLSS mod is required for this game to work with OptiScaler.',
  'optiscaler-trails-in-the-sky-1st-chapter-fsr2-resolution-scale':
    'Set the in-game resolution scale below 100% so OptiScaler can detect the FSR 2 input.',
  'optiscaler-trepang2-dx12-preset':
    'At launch, the game can reset the selected preset to Performance. Check the preset in the OptiScaler overlay. If this happens, select another preset, then select the desired one again.',
  'optiscaler-trine-5-dlss-mode':
    "Before installation, edit %APPDATA%\\Trine5\\options.txt. To enable DLSS, use setOption(rendererModule, 'DlssMode', x) with x from 0–4.",
  'optiscaler-until-dawn-fsr4-flicker':
    'When using FSR 4, select the Non-Linear sRGB input color space to fix flicker in some scenes.',
  'optiscaler-vampyr-antialiasing': 'Select TXAA 6× anti-aliasing in the game settings.',
  'optiscaler-voidtrain-dx12-mode': 'Use the game’s DX12 mode.',
  'optiscaler-way-of-the-hunter-dx12-fsr2-dx11-crash':
    'Run the game in DX12 mode; FSR2 inputs crash in DX11.',
  'optiscaler-welcome-to-the-game-iii-taa-dlss': 'Enable both TAA and DLSS in the game settings.',
  'optiscaler-wicked-island-optifg-dlssg-inputs':
    'Use OptiFG inputs; DLSSG inputs are unsupported.',
  'optiscaler-xuan-yuan-sword-vii-dx12-mode': 'Use the game’s DX12 mode.',
} as const;
export const OPTISCALER_MESSAGE_CONTEXTS = {
  'optiscaler-1666-amsterdam-fsr4-color-space': 'compatibility',
  'optiscaler-akimbot-taa-dlss': 'game_setting',
  'optiscaler-alone-in-the-dark-2024-dx12-dlss': 'compatibility',
  'optiscaler-apocalypse-2-0-display-res-mv': 'game_setting',
  'optiscaler-assassins-creed-origins-dlss-mod': 'compatibility',
  'optiscaler-assassins-creed-shadows-overlay-hdr': 'game_setting',
  'optiscaler-assetto-corsa-evo-fsr4-autoexposure': 'game_setting',
  'optiscaler-asterigos-fsr2-detection': 'game_setting',
  'optiscaler-automate-it-fsr-detection': 'game_setting',
  'optiscaler-batora-lost-haven-dx12': 'compatibility',
  'optiscaler-blades-of-fire-overlay-keyboard': 'game_setting',
  'optiscaler-bloodstained-frame-smoothing': 'game_setting',
  'optiscaler-blue-protocol-star-resonance-shaders': 'compatibility',
  'optiscaler-bright-memory-dx12-ray-tracing': 'compatibility',
  'optiscaler-brothers-remake-fsr4-color-space': 'game_setting',
  'optiscaler-car-mechanic-simulator-2026-single-player-demo-fsr3-mode': 'compatibility',
  'optiscaler-chernobylite-2-cinematic-reflections': 'game_setting',
  'optiscaler-chionophile-dx12': 'compatibility',
  'optiscaler-chip-n-clawz-fsr4-color-space': 'game_setting',
  'optiscaler-cions-of-vega-dx12': 'compatibility',
  'optiscaler-crash-bandicoot-4-antialiasing': 'game_setting',
  'optiscaler-crimson-oath-fsr4-color-space': 'game_setting',
  'optiscaler-curse-of-the-abandoned-floor-upscale-ratio': 'game_setting',
  'optiscaler-cyberpunk-fsr4-input': 'compatibility',
  'optiscaler-daemon-x-machina-titanic-scion-fsr4-color-space': 'game_setting',
  'optiscaler-darksiders-3-antialiasing': 'game_setting',
  'optiscaler-dawn-break-demo-dx12-motion-blur-color-space': 'compatibility',
  'optiscaler-ddod-3d-resolution': 'game_setting',
  'optiscaler-dead-rising-deluxe-remaster-root-signature': 'compatibility',
  'optiscaler-dead-space-2023-motion-blur': 'game_setting',
  'optiscaler-dead-take-fsr4-color-space': 'game_setting',
  'optiscaler-deadzone-rogue-frame-generation': 'game_setting',
  'optiscaler-death-stranding-2-xess-input': 'compatibility',
  'optiscaler-deconstruction-simulator-fsr4-color-space': 'game_setting',
  'optiscaler-deliver-us-mars-dx12': 'compatibility',
  'optiscaler-deliver-us-the-moon-dx12': 'compatibility',
  'optiscaler-destroy-all-humans-2-reprobed-dx12': 'compatibility',
  'optiscaler-devil-may-cry-5-reframework-pdperfplugin': 'compatibility',
  'optiscaler-diablo-iv-dx12': 'compatibility',
  'optiscaler-dream-eaters-fsr4-color-space': 'game_setting',
  'optiscaler-duskfade-demo-fsr-frame-generation': 'compatibility',
  'optiscaler-echoes-of-the-end-fsr4-color-space': 'game_setting',
  'optiscaler-elden-ring-erss-fg-mod': 'compatibility',
  'optiscaler-escape-simulator-2-demo-dynamic-resolution': 'game_setting',
  'optiscaler-evil-west-dx12': 'compatibility',
  'optiscaler-f1-22-dlss-quality': 'game_setting',
  'optiscaler-final-fantasy-xvi-fsr4-color-space': 'game_setting',
  'optiscaler-finnish-cottage-simulator-fsr4-color-space': 'game_setting',
  'optiscaler-five-nights-at-freddys-security-breach-dlss': 'game_setting',
  'optiscaler-fixforce-frame-generation': 'compatibility',
  'optiscaler-flipscapes-input-detection': 'game_setting',
  'optiscaler-forgive-me-father-2-dx12-fsr4': 'compatibility',
  'optiscaler-frostpunk-2-fsr4-color-space': 'game_setting',
  'optiscaler-frozenheim-dx12': 'compatibility',
  'optiscaler-funko-fusion-fsr4-color-space': 'game_setting',
  'optiscaler-ghost-recon-wildlands-dlss-mod': 'compatibility',
  'optiscaler-ghostrunner-2-dx12-performance': 'compatibility',
  'optiscaler-gothic-1-remake-sharpening': 'game_setting',
  'optiscaler-greedland-input-reload': 'game_setting',
  'optiscaler-grid-legends-antialiasing': 'game_setting',
  'optiscaler-gta-iii-definitive-city-glow': 'game_setting',
  'optiscaler-gta-san-andreas-definitive-city-glow': 'game_setting',
  'optiscaler-gta-vice-city-definitive-city-glow': 'game_setting',
  'optiscaler-hello-neighbor-2-dlss': 'game_setting',
  'optiscaler-highrise-city-dx12': 'compatibility',
  'optiscaler-hold-your-own-dlss': 'game_setting',
  'optiscaler-immortals-of-aveum-upscaler-reset': 'game_setting',
  'optiscaler-influx-redux-fsr3-water-flicker': 'game_setting',
  'optiscaler-jedi-survivor-restart': 'compatibility',
  'optiscaler-jedi-survivor-windowed': 'game_setting',
  'optiscaler-judgment-input': 'compatibility',
  'optiscaler-kiborg-fsr4-color-space': 'game_setting',
  'optiscaler-kiln-temporal-upscaling': 'game_setting',
  'optiscaler-kunitsu-gami-root-signature': 'game_setting',
  'optiscaler-land-of-the-vikings-dx12-model-5': 'compatibility',
  'optiscaler-lego-batman-xefg': 'game_setting',
  'optiscaler-liminalcore-fsr31-crash-fix': 'game_setting',
  'optiscaler-lost-judgment-input': 'game_setting',
  'optiscaler-lost-records-input': 'compatibility',
  'optiscaler-lumina-veil-frame-generation': 'compatibility',
  'optiscaler-lunar-eclipse-frame-generation': 'compatibility',
  'optiscaler-martha-is-dead-fsr4-color-space': 'game_setting',
  'optiscaler-metal-gear-solid-delta-dlss-quality': 'game_setting',
  'optiscaler-morbid-metal-dlss-restart': 'game_setting',
  'optiscaler-mr-photographer-dx11': 'compatibility',
  'optiscaler-oddroom-dx12': 'compatibility',
  'optiscaler-oddsparks-fsr4-color-space': 'game_setting',
  'optiscaler-onimusha-way-of-the-sword-reframework': 'compatibility',
  'optiscaler-online-404-reselect-upscaler': 'game_setting',
  'optiscaler-pax-autocratica-prologue-dlss-input': 'compatibility',
  'optiscaler-payday-3-fsr-input': 'compatibility',
  'optiscaler-planet-coaster-2-dlss-input': 'compatibility',
  'optiscaler-polaris-demo-inputs': 'compatibility',
  'optiscaler-project-songbird-teaser-faceless-dynamic-resolution': 'game_setting',
  'optiscaler-project-station-demo-dx12': 'compatibility',
  'optiscaler-psalm-2-dlss-input': 'compatibility',
  'optiscaler-psycho-fear-fsr4-input-color-space': 'compatibility',
  'optiscaler-quarantine-zone-the-last-check-fsr4-input-color-space': 'compatibility',
  'optiscaler-raji-an-ancient-epic-dlss-input': 'compatibility',
  'optiscaler-ready-or-not-resolution-scale': 'game_setting',
  'optiscaler-realmwalker-taa-dlss': 'game_setting',
  'optiscaler-red-dead-redemption-2-vulkan-reflex': 'game_setting',
  'optiscaler-redout-2-xess-artifacts': 'compatibility',
  'optiscaler-resident-evil-2-remake-reframework-upscalerbase-plugin': 'compatibility',
  'optiscaler-resident-evil-3-remake-reframework-upscalerbase-plugin': 'compatibility',
  'optiscaler-resident-evil-4-remake-reframework-upscalerbase-plugin': 'compatibility',
  'optiscaler-resident-evil-7-reframework-upscalerbase-plugin': 'compatibility',
  'optiscaler-resident-evil-requiem-reframework': 'compatibility',
  'optiscaler-riven-fsr4-non-linear-srgb-input': 'compatibility',
  'optiscaler-robocop-rogue-city-unfinished-business-fsr4-balanced-flicker': 'compatibility',
  'optiscaler-roboquest-antialiasing': 'game_setting',
  'optiscaler-romancelvania-dx12': 'compatibility',
  'optiscaler-romeo-is-a-dead-man-anti-aliasing': 'game_setting',
  'optiscaler-saints-row-2022-dx12-fsr4': 'compatibility',
  'optiscaler-scathe-dx12-fsr-input': 'compatibility',
  'optiscaler-scp-secret-files-dx12': 'compatibility',
  'optiscaler-sekiro-shadows-die-twice-sekirotsr-mod': 'compatibility',
  'optiscaler-shadow-warrior-3-dx12': 'compatibility',
  'optiscaler-shatterline-dx11-upscaler-quality': 'compatibility',
  'optiscaler-smile-protocol-demo-xefg': 'compatibility',
  'optiscaler-sons-of-the-forest-inventory': 'compatibility',
  'optiscaler-soulslinger-envoy-of-death-fsr4-non-linear-srgb-input': 'compatibility',
  'optiscaler-spyro-reignited-antialiasing': 'game_setting',
  'optiscaler-stalker-call-of-prypiat-enhanced-edition-dlss-input': 'compatibility',
  'optiscaler-stalker-clear-sky-enhanced-edition-dlss-input': 'compatibility',
  'optiscaler-stalker-shadow-of-chornobyl-enhanced-edition-dlss-input': 'compatibility',
  'optiscaler-star-wars-zero-company-vendor-options': 'compatibility',
  'optiscaler-steelrising-fsr4-color-space': 'compatibility',
  'optiscaler-stranded-alien-dawn-fsr2-input': 'compatibility',
  'optiscaler-styx-blades-of-greed-fsr4-non-linear-srgb-input': 'compatibility',
  'optiscaler-sumerian-six-fsr4-non-linear-srgb-input': 'compatibility',
  'optiscaler-system-shock-remake-dx11': 'compatibility',
  'optiscaler-tainted-grail-dx12-skybox': 'compatibility',
  'optiscaler-tchia-xess-corruption': 'compatibility',
  'optiscaler-tekken-8-fsr4-artifacts': 'compatibility',
  'optiscaler-tempest-rising-fsr4-non-linear-srgb-input': 'compatibility',
  'optiscaler-terratech-legion-fsr4-non-linear-color-space': 'compatibility',
  'optiscaler-the-alley-demo-frame-generation': 'game_setting',
  'optiscaler-the-alters-dlss-input': 'compatibility',
  'optiscaler-the-chant-fsr2-shimmer': 'compatibility',
  'optiscaler-the-hollow-complex-demo-fsr3-input': 'compatibility',
  'optiscaler-the-medium-dx12': 'compatibility',
  'optiscaler-the-occultist-fsr4-non-linear-srgb-input-color-space': 'game_setting',
  'optiscaler-the-orville-interactive-fan-experience-dx12-launch-option': 'compatibility',
  'optiscaler-tormented-souls-2-dx11': 'compatibility',
  'optiscaler-total-war-warhammer-3-warhammer3dlss-mod': 'compatibility',
  'optiscaler-trails-in-the-sky-1st-chapter-fsr2-resolution-scale': 'game_setting',
  'optiscaler-trepang2-dx12-preset': 'compatibility',
  'optiscaler-trine-5-dlss-mode': 'game_setting',
  'optiscaler-until-dawn-fsr4-flicker': 'compatibility',
  'optiscaler-vampyr-antialiasing': 'game_setting',
  'optiscaler-voidtrain-dx12-mode': 'compatibility',
  'optiscaler-way-of-the-hunter-dx12-fsr2-dx11-crash': 'compatibility',
  'optiscaler-welcome-to-the-game-iii-taa-dlss': 'game_setting',
  'optiscaler-wicked-island-optifg-dlssg-inputs': 'compatibility',
  'optiscaler-xuan-yuan-sword-vii-dx12-mode': 'compatibility',
} as const;

export type OptiScalerSourceCatalog = typeof OPTISCALER_SOURCE_CATALOG;
export type OptiScalerMessageKey = keyof OptiScalerSourceCatalog;
export type OptiScalerMessageContext = (typeof OPTISCALER_MESSAGE_CONTEXTS)[OptiScalerMessageKey];
export type OptiScalerTranslations = Readonly<Record<OptiScalerMessageKey, string>>;
